In [1]:
import numpy as np
a = np.array([1, 2, 3, 4, 5]) 
print(a)
print(type(a))
print(a.dtype)
print(a.shape)
#разные способы создать массив:
print(np.zeros(5))
print(np.ones(5))
print(np.arange(0, 10, 2))
print(np.linspace(0, 1, 5))
print(np.random.randint(0, 100, 10))


[1 2 3 4 5]
<class 'numpy.ndarray'>
int64
(5,)
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[ 4 98 88 32 98 29 28 73 14 49]


arrange отличается от linspace тем, что arange создаёт последовательность с заданным шагом, а linspace задаётся количество "отрезков", на которое надо разбить промежуток, заданный первыми двумя числами.

In [2]:
m = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print(m)
print(m.shape)
print(m[0])
print(m[1][2])
print(m[:, 1]) # весь второй столбец
print()
a = np.arange(10)
print(a[1:4])
print(a[::2])
print(a[-1])
print(a[::-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
[1 2 3]
6
[2 5 8]

[1 2 3]
[0 2 4 6 8]
9
[9 8 7 6 5 4 3 2 1 0]


m[:, 1] выбирает все 1-е элементы в каждой строке этого двумерного массива. (Т.к. в памяти двумерный массив - одномерный. И каждый раз каретка передвигается на новую часть односвязной области памяти на 1-ый элемент)

In [3]:
a = np.array([1, 2, 3, 4, 5])
print(a * 2)
print(a + 2)
print(a ** 2)
print(a > 3) # выведет [False False False  True  True]

lst = [1, 2, 3, 4, 5]
print(lst * 2)


[ 2  4  6  8 10]
[3 4 5 6 7]
[ 1  4  9 16 25]
[False False False  True  True]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


NumPy array: * 2 - математическая операция над каждым элементом.
Python list:  * 2 - операция повторения (как строка * 2).
Это разные операторы для разных типов данных.

In [4]:
data = np.random.randint(0, 100, 50)

print("Среднее: ", np.mean(data))
print("Стандарт. отклонение: ", np.std(data))
print("Мин: ", np.min(data))
print("Макс: ", np.max(data))
print("Медиана: ", np.percentile(data, 50))
print("25-й персентиль: ", np.percentile(data, 25))
print("75-й персентиль: ", np.percentile(data, 75))

Среднее:  49.56
Стандарт. отклонение:  29.75376278725096
Мин:  0
Макс:  97
Медиана:  56.0
25-й персентиль:  22.5
75-й персентиль:  73.0


Стандартное отклонение - это отклонение элементов от среднего значения всех элементов.

In [5]:
import pandas as pd

df = pd.read_csv('train.csv')

arr = df["Age"].dropna().values

print(type(arr))
print(arr.shape)

<class 'numpy.ndarray'>
(714,)


In [6]:
print("NumPy mean = ", np.mean(arr))
print("Std =", np.std(arr))
print("Percentile 25/50/75 = ", np.percentile(arr, [25, 50, 75]))

NumPy mean =  29.69911764705882
Std = 14.516321150817316
Percentile 25/50/75 =  [20.125 28.    38.   ]


In [7]:
print("\npandas describe")
print(df["Age"].describe())
print(type(df["Age"]))


pandas describe
count    714.000000
mean      29.699118
std       14.526497
min        0.420000
25%       20.125000
50%       28.000000
75%       38.000000
max       80.000000
Name: Age, dtype: float64
<class 'pandas.Series'>


Все данные формата numpy.ndarray практически идеально совпадают с pandas.Series. Разница появляется при округлении.

In [8]:
df["Is_child"] = np.where(df["Age"] < 18, 1, 0)
print(df['Is_child'].value_counts())
#df['Age_group'] = df['Age'].apply(lambda x: 'child' if x < 18 else 'adult')- было

Is_child
0    778
1    113
Name: count, dtype: int64


метод np.where() удобнее apply/lambda тем, что он короче. Мы просто пишем условие, 1 - если оно соблюдено (берём в свой новый столбец), 0 - если наоборот.

In [9]:
arr_with_nan = df['Age'].values          # с NaN
arr_clean = df['Age'].dropna().values    # без NaN

print(np.mean(arr_with_nan))   # nan — бесполезно
print(np.mean(arr_clean))      # 29.69 — нормально
# ```

# В конспект одна строка:
# ```
# .values → конвертирует Series в numpy array (убирает индекс)
# Всегда делай .dropna().values если есть пропуски

nan
29.69911764705882


In [4]:
import numpy as np
print(np.__version__)
print(np.show_config())

2.4.2
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-7so2u9ys/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-7so2u9ys/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.31.dev  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=24
    pc file directory: D:/a/numpy-release/numpy-release/.openblas
    version: 0.3.31.dev
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-7so2u9ys/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-7so2u9ys/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas conf

In [3]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
arr = np.zeros(10)
arr[5] = 1 # если именно 5-ый в значении "с номером 5", если в принципе 5-ый, то индекс будет 4
print(arr)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [6]:
print(np.arange(10, 50))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [7]:
print([1, 2, 3, 4, 5][::-1])

[5, 4, 3, 2, 1]


In [10]:
arr = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]])
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [11]:
arr = [1, 2, 0, 0, 4, 0]
print([x for x in arr if x != 0])

[1, 2, 4]


In [19]:
arr = np.ones((3, 3)).astype('bool')
print(arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [22]:
arr = np.linspace(0, 1, 11)[1:-1]
print(arr)

[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [29]:
arr = np.random.randint(0, 100, 10)
arr.sort()
print(arr)

[26 33 37 53 65 82 89 90 95 96]


In [31]:
arr = np.array([
    [1, 0, 0],
    [0, 0, 0],
    [0, 0, 1]
]) # если имеется ввиду, что границы - это начало и конец, а не сверху и снизу тоже
print(arr)

[[1 0 1]
 [1 0 1]
 [1 0 1]]


In [42]:
arr = np.arange(0, 11)
print([int(x) for x in arr if x > 5])

[6, 7, 8, 9, 10]


In [45]:
arr_1 = [1, 2, 3]
arr_2 = [4, 5, 6]
print([arr_1[i] + arr_2[i] for i in range(len(arr_1))])

[5, 7, 9]


In [49]:
arr = [int(x) for x in np.random.randint(0, 100, 10)]
print(max(arr), min(arr), arr.index(max(arr)), arr.index(min(arr)))

94 6 4 9


In [51]:
arr = np.arange(0, 9).reshape((3, 3))
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [52]:
arr = np.random.randint(0, 100, 10)
print((arr - arr.min()) / (arr.max() - arr.min()))

[0.68478261 1.         0.77173913 0.         0.2826087  0.07608696
 0.82608696 0.92391304 0.95652174 0.45652174]


In [69]:
arr_1 = np.array([
    [1, 2],
    [3, 4]
])

arr_2 = np.array([
    [5, 6],
    [7, 8]
])

new_matrix = np.array([
    [sum(arr_1[0][:] * arr_2.transpose()[0][:]), sum(arr_1[0][:] * arr_2.transpose()[1][:])],
    [sum(arr_1[1][:] * arr_2.transpose()[0][:]), sum(arr_1[1][:] * arr_2.transpose()[1][:])]
])
print(new_matrix)

[[19 22]
 [43 50]]


In [73]:
arr = np.arange(0, 10)
for i in range(len(arr)):
    if arr[i] % 2 == 0:
        arr[i] = -1
print(arr)

[-1  1 -1  3 -1  5 -1  7 -1  9]


In [74]:
arr = np.zeros(10)
arr[3], arr[5], arr[7] = 5, 5, 5
print(arr)

[0. 0. 0. 5. 0. 5. 0. 5. 0. 0.]


In [75]:
arr_1, arr_2 = [1,2,3,4,5], [3,4,5,6,7]
print(list(set(arr_1)&set(arr_2)))

[3, 4, 5]
